# Generated by Django 3.2.5 on 2021-08-11 10:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0029_auto_20210811_1607'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.TextField(max_length=200)),
                ('enforce_restrictions', models.BooleanField()),
                ('budget_type', models.TextField(max_length=100)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 37, 35, 671312, tzinfo=utc))),
                ('authoriser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.year_master')),
            ],
            options={
                'unique_together': {('id', 'company_master_id')},
            },
        ),
        migrations.CreateModel(
            name='revised_budget_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('feb', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('mar', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('apr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('may', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('jun', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('jul', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('aug', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('sep', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('octo', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('nov', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('dec', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 37, 35, 672310, tzinfo=utc))),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budget')),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
                ('ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master')),
            ],
            options={
                'unique_together': {('budget_id', 'company_master_id')},
            },
        ),
        migrations.CreateModel(
            name='revised_budget_cashflow_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('feb', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('mar', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('apr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('may', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('jun', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('jul', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('aug', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('sep', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('octo', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('nov', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('dec', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('budget_type', models.TextField(max_length=100)),
                ('cashflow_head', models.TextField(max_length=100)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 37, 35, 674304, tzinfo=utc))),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budget')),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
                ('ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master')),
            ],
            options={
                'unique_together': {('budget_id', 'cashflow_head')},
            },
        ),
        migrations.CreateModel(
            name='budget_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('feb', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('mar', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('apr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('may', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('jun', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('jul', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('aug', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('sep', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('octo', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('nov', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('dec', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 37, 35, 672310, tzinfo=utc))),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budget')),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
                ('ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master')),
            ],
            options={
                'unique_together': {('budget_id', 'company_master_id')},
            },
        ),
        migrations.CreateModel(
            name='budget_cashflow_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('feb', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('mar', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('apr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('may', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('jun', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('jul', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('aug', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('sep', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('octo', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('nov', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('dec', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('budget_type', models.TextField(max_length=100)),
                ('cashflow_head', models.TextField(max_length=100)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 37, 35, 673308, tzinfo=utc))),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budget')),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
                ('ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master')),
            ],
            options={
                'unique_together': {('budget_id', 'cashflow_head')},
            },
        ),
    ]
