# Generated by Django 3.2.5 on 2021-08-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Budget', '0001_initial'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revised_budget_details',
            name='ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master'),
        ),
        migrations.AddField(
            model_name='revised_budget_cashflow_details',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budget'),
        ),
        migrations.AddField(
            model_name='revised_budget_cashflow_details',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='revised_budget_cashflow_details',
            name='ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master'),
        ),
        migrations.AddField(
            model_name='historicalrevised_budget_details',
            name='budget_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Budget.budget'),
        ),
    ]
