# Generated by Django 3.2.5 on 2021-08-11 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 693174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='budget_cashflow_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 695170, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='budget_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 694174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revised_budget_cashflow_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 696169, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revised_budget_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 694174, tzinfo=utc)),
        ),
    ]
