# Generated by Django 3.2.5 on 2021-08-12 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Budget', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrevised_budget_details',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrevised_budget_details',
            name='ledger_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.ledger_master'),
        ),
        migrations.AddField(
            model_name='historicalrevised_budget_cashflow_details',
            name='budget_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Budget.budget'),
        ),
        migrations.AddField(
            model_name='historicalrevised_budget_cashflow_details',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalrevised_budget_cashflow_details',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrevised_budget_cashflow_details',
            name='ledger_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.ledger_master'),
        ),
        migrations.AddField(
            model_name='historicalbudget_details',
            name='budget_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Budget.budget'),
        ),
        migrations.AddField(
            model_name='historicalbudget_details',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalbudget_details',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbudget_details',
            name='ledger_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.ledger_master'),
        ),
        migrations.AddField(
            model_name='historicalbudget_cashflow_details',
            name='budget_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Budget.budget'),
        ),
        migrations.AddField(
            model_name='historicalbudget_cashflow_details',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalbudget_cashflow_details',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbudget_cashflow_details',
            name='ledger_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.ledger_master'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='authoriser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='year_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.year_master'),
        ),
        migrations.AddField(
            model_name='budget_details',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budget'),
        ),
        migrations.AddField(
            model_name='budget_details',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='budget_details',
            name='ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master'),
        ),
        migrations.AddField(
            model_name='budget_cashflow_details',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budget.budget'),
        ),
        migrations.AddField(
            model_name='budget_cashflow_details',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='budget_cashflow_details',
            name='ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master'),
        ),
        migrations.AddField(
            model_name='budget',
            name='authoriser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='budget',
            name='year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.year_master'),
        ),
        migrations.AlterUniqueTogether(
            name='revised_budget_details',
            unique_together={('budget_id', 'ledger_id')},
        ),
        migrations.AlterUniqueTogether(
            name='revised_budget_cashflow_details',
            unique_together={('budget_id', 'cashflow_head')},
        ),
        migrations.AlterUniqueTogether(
            name='budget_details',
            unique_together={('budget_id', 'ledger_id')},
        ),
        migrations.AlterUniqueTogether(
            name='budget_cashflow_details',
            unique_together={('budget_id', 'cashflow_head')},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('id', 'company_master_id')},
        ),
    ]
