# Generated by Django 3.2.5 on 2021-08-14 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0006_auto_20210814_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 636031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='budget_cashflow_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 657481, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='budget_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 643001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 636031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalbudget_cashflow_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 657481, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalbudget_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 643001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalrevised_budget_cashflow_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 665048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalrevised_budget_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 648264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revised_budget_cashflow_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 665048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revised_budget_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 648264, tzinfo=utc)),
        ),
    ]
