# Generated by Django 3.2.5 on 2021-08-14 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0008_auto_20210814_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 337880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='budget_cashflow_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 359730, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='budget_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 343690, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 337880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalbudget_cashflow_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 359730, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalbudget_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 343690, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalrevised_budget_cashflow_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 369098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalrevised_budget_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 351669, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revised_budget_cashflow_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 369098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='revised_budget_details',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 351669, tzinfo=utc)),
        ),
    ]
