# Generated by Django 3.2.5 on 2021-09-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0011_auto_20210814_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_details',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_detail', to='Budget.budget'),
        ),
    ]
