# Generated by Django 3.2.5 on 2021-09-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0014_cashflow_heads_historicalcashflow_heads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget_cashflow_details',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='historicalbudget_cashflow_details',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='historicalrevised_budget_cashflow_details',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='revised_budget_cashflow_details',
            name='ledger_id',
        ),
    ]
