# Generated by Django 3.2.5 on 2021-09-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0015_auto_20210903_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_cashflow_details',
            name='cashflow_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Budget.cashflow_heads'),
        ),
        migrations.AlterField(
            model_name='historicalbudget_cashflow_details',
            name='cashflow_head',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Budget.cashflow_heads'),
        ),
        migrations.AlterField(
            model_name='historicalrevised_budget_cashflow_details',
            name='cashflow_head',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Budget.cashflow_heads'),
        ),
        migrations.AlterField(
            model_name='revised_budget_cashflow_details',
            name='cashflow_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Budget.cashflow_heads'),
        ),
    ]
