# Generated by Django 3.2.5 on 2021-09-04 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0021_auto_20210904_1328'),
        ('Budget', '0017_auto_20210904_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='authoriser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.year_master'),
        ),
        migrations.AlterField(
            model_name='budget_cashflow_details',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Budget.budget'),
        ),
        migrations.AlterField(
            model_name='budget_cashflow_details',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='budget_details',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_detail', to='Budget.budget'),
        ),
        migrations.AlterField(
            model_name='budget_details',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='budget_details',
            name='ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.ledger_master'),
        ),
        migrations.AlterField(
            model_name='revised_budget_cashflow_details',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Budget.budget'),
        ),
        migrations.AlterField(
            model_name='revised_budget_cashflow_details',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='revised_budget_details',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Budget.budget'),
        ),
        migrations.AlterField(
            model_name='revised_budget_details',
            name='company_master_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='revised_budget_details',
            name='ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.ledger_master'),
        ),
    ]
