# Generated by Django 3.2.5 on 2021-09-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0021_auto_20210904_1328'),
        ('Budget', '0018_auto_20210904_1328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('company_master_id', 'year_id', 'budget_type')},
        ),
    ]
