# Generated by Django 3.2.5 on 2021-07-28 21:06

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions', models.TextField(max_length=200)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 129330, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='user_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group_name', models.TextField(max_length=200)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 128330, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 124331, tzinfo=utc))),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='user_right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdated_days', models.IntegerField(null=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_alter', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=False)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 130333, tzinfo=utc))),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.transaction_right')),
                ('user_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user_group')),
            ],
        ),
    ]
