# Generated by Django 3.2.5 on 2021-07-29 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_right',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 867140, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.TextField(default='primary', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 864100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 866139, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_right',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 867140, tzinfo=utc)),
        ),
    ]
