# Generated by Django 3.2.5 on 2021-08-13 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210812_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser_group',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicaluser_right',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_group',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_right',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 409553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 410550, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 410550, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 410550, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 409553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 410550, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 410550, tzinfo=utc)),
        ),
    ]
