# Generated by Django 3.2.5 on 2021-07-29 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210729_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_right',
            name='backdated_days',
        ),
        migrations.AddField(
            model_name='user_group',
            name='backdated_days',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 10, 22, 18, 836791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 10, 22, 18, 831787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 10, 22, 18, 835790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 10, 22, 18, 837791, tzinfo=utc)),
        ),
    ]
