# Generated by Django 3.2.5 on 2021-08-14 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210813_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 20879, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 27974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_group',
            name='user_group_name',
            field=models.TextField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaluser_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 31430, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 30388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 20879, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 27974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='user_group_name',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 31430, tzinfo=utc)),
        ),
    ]
