# Generated by Django 3.2.5 on 2021-08-14 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210814_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 492904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 501811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 502850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 502850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 492904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 501811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 502850, tzinfo=utc)),
        ),
    ]
