# Generated by Django 3.2.5 on 2021-08-14 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20210814_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 37, 29, 606703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 37, 29, 617133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 37, 29, 621425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 37, 29, 620069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 37, 29, 606703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 37, 29, 617133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 37, 29, 621425, tzinfo=utc)),
        ),
    ]
