# Generated by Django 3.2.5 on 2021-08-01 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20210731_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 394386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 391388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 394386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 395386, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='user_right',
            unique_together={('user_group_id', 'transaction_id')},
        ),
    ]
