# Generated by Django 3.2.5 on 2021-08-05 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20210804_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_group_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group_name', models.TextField(max_length=200)),
                ('backdated_days', models.IntegerField(default=1, null=True)),
                ('altered_by', models.TextField()),
                ('altered_on', models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 901815, tzinfo=utc))),
                ('entry', models.TextField(default='before')),
                ('is_deleted', models.BooleanField(default=False)),
                ('operation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_superuser', models.BooleanField()),
                ('altered_by', models.TextField()),
                ('altered_on', models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 897817, tzinfo=utc))),
                ('entry', models.TextField(default='before')),
                ('is_deleted', models.BooleanField(default=False)),
                ('operation', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 904815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 885817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 898816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 905815, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='user_right_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False)),
                ('can_alter', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=False)),
                ('altered_by', models.TextField()),
                ('altered_on', models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 908816, tzinfo=utc))),
                ('entry', models.TextField(default='before')),
                ('is_deleted', models.BooleanField(default=False)),
                ('operation', models.TextField()),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.transaction_right')),
                ('user_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user_group')),
            ],
        ),
    ]
