# Generated by Django 3.2.5 on 2021-08-06 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_auto_20210805_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 7, 35, 17, 729277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 7, 35, 17, 725276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 7, 35, 17, 728277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_group_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 7, 35, 17, 728277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 7, 35, 17, 727276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_right',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 7, 35, 17, 730278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_right_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 7, 35, 17, 731276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_right_logs',
            name='transaction_id',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_right_logs',
            name='user_group_id',
            field=models.TextField(max_length=500),
        ),
    ]
