# Generated by Django 3.2.5 on 2021-08-12 08:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lc',
            fields=[
                ('lc_no', models.AutoField(primary_key=True, serialize=False)),
                ('trans_type', models.TextField(max_length=1000)),
                ('lc_date', models.DateField()),
                ('applicant_bank', models.TextField(max_length=1000, null=True)),
                ('benificiary_bank', models.TextField(max_length=1000, null=True)),
                ('benificiary_bank_lc_no', models.TextField(max_length=1000)),
                ('applicant_bank_lc_no', models.TextField(max_length=1000)),
                ('inspection', models.BooleanField(default=False, null=True)),
                ('bank_ref', models.TextField(max_length=1000)),
                ('days_for_submit_to_bank', models.IntegerField(max_length=10000000)),
                ('payment_terms', models.TextField(max_length=50000)),
                ('place_of_taking_incharge', models.TextField(max_length=1000)),
                ('final_destination_of_delivery', models.TextField(max_length=10000)),
                ('completed', models.BooleanField(default=False)),
                ('shipment_terms', models.TextField(max_length=10000000)),
                ('goods_description', models.TextField(max_length=10000000)),
                ('other_lc_terms', models.TextField(max_length=10000000)),
                ('expiry_date', models.DateField()),
                ('lc_amount', models.FloatField(max_length=100000000)),
                ('created_by', models.TextField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 8, 59, 11, 755537, tzinfo=utc))),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.cost_center')),
                ('party_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master')),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.year_master')),
            ],
            options={
                'unique_together': {('lc_no', 'company_master_id')},
            },
        ),
        migrations.CreateModel(
            name='lc_docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=500)),
                ('file', models.FileField(upload_to='lc_files')),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 8, 59, 11, 755537, tzinfo=utc))),
                ('lc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.lc')),
            ],
        ),
        migrations.CreateModel(
            name='lc_amend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_no', models.BigIntegerField()),
                ('issue_date', models.DateField()),
                ('LDS', models.DateField()),
                ('expiry_date', models.DateField()),
                ('lc_amount', models.FloatField()),
                ('remarks', models.TextField()),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 8, 59, 11, 755537, tzinfo=utc))),
                ('lc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.lc')),
            ],
        ),
        migrations.CreateModel(
            name='Historicallc_docs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=500)),
                ('file', models.TextField(max_length=100)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 8, 59, 11, 755537, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lc_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lc.lc')),
            ],
            options={
                'verbose_name': 'historical lc_docs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicallc_amend',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amendment_no', models.BigIntegerField()),
                ('issue_date', models.DateField()),
                ('LDS', models.DateField()),
                ('expiry_date', models.DateField()),
                ('lc_amount', models.FloatField()),
                ('remarks', models.TextField()),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 8, 59, 11, 755537, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lc_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lc.lc')),
            ],
            options={
                'verbose_name': 'historical lc_amend',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicallc',
            fields=[
                ('lc_no', models.IntegerField(blank=True, db_index=True)),
                ('trans_type', models.TextField(max_length=1000)),
                ('lc_date', models.DateField()),
                ('applicant_bank', models.TextField(max_length=1000, null=True)),
                ('benificiary_bank', models.TextField(max_length=1000, null=True)),
                ('benificiary_bank_lc_no', models.TextField(max_length=1000)),
                ('applicant_bank_lc_no', models.TextField(max_length=1000)),
                ('inspection', models.BooleanField(default=False, null=True)),
                ('bank_ref', models.TextField(max_length=1000)),
                ('days_for_submit_to_bank', models.IntegerField(max_length=10000000)),
                ('payment_terms', models.TextField(max_length=50000)),
                ('place_of_taking_incharge', models.TextField(max_length=1000)),
                ('final_destination_of_delivery', models.TextField(max_length=10000)),
                ('completed', models.BooleanField(default=False)),
                ('shipment_terms', models.TextField(max_length=10000000)),
                ('goods_description', models.TextField(max_length=10000000)),
                ('other_lc_terms', models.TextField(max_length=10000000)),
                ('expiry_date', models.DateField()),
                ('lc_amount', models.FloatField(max_length=100000000)),
                ('created_by', models.TextField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 8, 59, 11, 755537, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_master_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master')),
                ('cost_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.cost_center')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.ledger_master')),
                ('year_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.year_master')),
            ],
            options={
                'verbose_name': 'historical lc',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
