# Generated by Django 3.2.5 on 2021-08-07 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0023_auto_20210807_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='lc',
            fields=[
                ('lc_no', models.AutoField(primary_key=True, serialize=False)),
                ('trans_type', models.TextField(max_length=1000)),
                ('lc_date', models.DateField()),
                ('applicant_bank', models.TextField(max_length=1000, null=True)),
                ('benificiary_bank', models.TextField(max_length=1000, null=True)),
                ('benificiary_bank_lc_no', models.TextField(max_length=1000)),
                ('applicant_bank_lc_no', models.TextField(max_length=1000)),
                ('inspection', models.BooleanField(default=False, null=True)),
                ('bank_ref', models.TextField(max_length=1000)),
                ('days_for_submit_to_bank', models.IntegerField(max_length=10000000)),
                ('payment_terms', models.TextField(max_length=50000)),
                ('place_of_taking_incharge', models.TextField(max_length=1000)),
                ('final_destination_of_delivery', models.TextField(max_length=10000)),
                ('completed', models.BooleanField(default=False)),
                ('shipment_terms', models.TextField(max_length=10000000)),
                ('goods_description', models.TextField(max_length=10000000)),
                ('other_lc_terms', models.TextField(max_length=10000000)),
                ('expiry_date', models.DateField()),
                ('lc_amount', models.FloatField(max_length=100000000)),
                ('created_by', models.TextField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 7, 8, 54, 59, 790551, tzinfo=utc))),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.cost_center')),
                ('party_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master')),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.year_master')),
            ],
            options={
                'unique_together': {('lc_no', 'company_master_id')},
            },
        ),
        migrations.CreateModel(
            name='lc_amend_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_id', models.TextField()),
                ('amendment_no', models.BigIntegerField()),
                ('issue_date', models.DateField()),
                ('LDS', models.DateField()),
                ('expiry_date', models.DateField()),
                ('lc_amount', models.FloatField()),
                ('remarks', models.TextField()),
                ('altered_by', models.TextField()),
                ('altered_on', models.DateTimeField(default=datetime.datetime(2021, 8, 7, 8, 54, 59, 793551, tzinfo=utc))),
                ('entry', models.TextField(default='before')),
                ('is_deleted', models.BooleanField(default=False)),
                ('operation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lc_docs_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=500)),
                ('file', models.FileField(upload_to='lc_files')),
                ('lc_id', models.TextField(max_length=10000)),
                ('altered_by', models.TextField()),
                ('altered_on', models.DateTimeField(default=datetime.datetime(2021, 8, 7, 8, 54, 59, 792551, tzinfo=utc))),
                ('entry', models.TextField(default='before')),
                ('is_deleted', models.BooleanField(default=False)),
                ('operation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lc_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_no', models.TextField(max_length=1000)),
                ('trans_type', models.TextField(max_length=1000)),
                ('lc_date', models.DateField()),
                ('year_id', models.TextField(max_length=1000)),
                ('party_code', models.TextField(max_length=1000)),
                ('cost_center', models.TextField(max_length=1000)),
                ('applicant_bank', models.TextField(max_length=1000, null=True)),
                ('benificiary_bank', models.TextField(max_length=1000, null=True)),
                ('benificiary_bank_lc_no', models.TextField(max_length=1000)),
                ('applicant_bank_lc_no', models.TextField(max_length=1000)),
                ('inspection', models.BooleanField(default=False, null=True)),
                ('bank_ref', models.TextField(max_length=1000)),
                ('days_for_submit_to_bank', models.IntegerField(max_length=10000000)),
                ('payment_terams', models.TextField(max_length=50000)),
                ('place_of_taking_incharge', models.TextField(max_length=1000)),
                ('final_destination_of_delivery', models.TextField(max_length=10000)),
                ('completed', models.BooleanField(default=False)),
                ('shipment_terms', models.TextField(max_length=10000000)),
                ('goods_description', models.TextField(max_length=10000000)),
                ('other_lc_terms', models.TextField(max_length=10000000)),
                ('bank_ac', models.TextField(max_length=1000)),
                ('expiry_date', models.DateField()),
                ('lc_amount', models.FloatField(max_length=100000000)),
                ('company_master_id', models.TextField(max_length=1000)),
                ('altered_by', models.TextField()),
                ('altered_on', models.DateTimeField(default=datetime.datetime(2021, 8, 7, 8, 54, 59, 791552, tzinfo=utc))),
                ('entry', models.TextField(default='before')),
                ('is_deleted', models.BooleanField(default=False)),
                ('operation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lc_docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=500)),
                ('file', models.FileField(upload_to='lc_files')),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 7, 8, 54, 59, 791552, tzinfo=utc))),
                ('lc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.lc')),
            ],
        ),
        migrations.CreateModel(
            name='lc_amend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_no', models.BigIntegerField()),
                ('issue_date', models.DateField()),
                ('LDS', models.DateField()),
                ('expiry_date', models.DateField()),
                ('lc_amount', models.FloatField()),
                ('remarks', models.TextField()),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 7, 8, 54, 59, 792551, tzinfo=utc))),
                ('lc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc.lc')),
            ],
        ),
    ]
