# Generated by Django 3.2.5 on 2021-08-07 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 10, 35, 42, 136223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 10, 35, 42, 139180, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 10, 35, 42, 139180, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 10, 35, 42, 138213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 10, 35, 42, 138213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 10, 35, 42, 137222, tzinfo=utc)),
        ),
    ]
