# Generated by Django 3.2.5 on 2021-08-10 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0002_auto_20210807_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 30, 47, 283693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 30, 47, 294663, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 30, 47, 296708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 30, 47, 288674, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 30, 47, 293662, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 30, 47, 286680, tzinfo=utc)),
        ),
    ]
