# Generated by Django 3.2.5 on 2021-08-13 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0002_auto_20210812_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallc',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicallc_amend',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicallc_docs',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lc',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lc_amend',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lc_docs',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicallc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 546456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicallc_amend',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 550465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicallc_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 550465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 546456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 550465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 3, 29, 11, 550465, tzinfo=utc)),
        ),
    ]
