# Generated by Django 3.2.5 on 2021-08-11 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0004_auto_20210811_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 378183, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 381175, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 381175, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 379180, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 381175, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 379180, tzinfo=utc)),
        ),
    ]
