# Generated by Django 3.2.5 on 2021-08-11 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0007_auto_20210811_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 671061, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 674090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 674090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 672096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 674090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 38, 38, 672096, tzinfo=utc)),
        ),
    ]
