# Generated by Django 3.2.5 on 2021-08-12 01:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0031_auto_20210812_0702'),
        ('lc', '0008_auto_20210811_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 113190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 113190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 113190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 113190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 113190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 113190, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Historicallc',
            fields=[
                ('lc_no', models.IntegerField(blank=True, db_index=True)),
                ('trans_type', models.TextField(max_length=1000)),
                ('lc_date', models.DateField()),
                ('applicant_bank', models.TextField(max_length=1000, null=True)),
                ('benificiary_bank', models.TextField(max_length=1000, null=True)),
                ('benificiary_bank_lc_no', models.TextField(max_length=1000)),
                ('applicant_bank_lc_no', models.TextField(max_length=1000)),
                ('inspection', models.BooleanField(default=False, null=True)),
                ('bank_ref', models.TextField(max_length=1000)),
                ('days_for_submit_to_bank', models.IntegerField(max_length=10000000)),
                ('payment_terms', models.TextField(max_length=50000)),
                ('place_of_taking_incharge', models.TextField(max_length=1000)),
                ('final_destination_of_delivery', models.TextField(max_length=10000)),
                ('completed', models.BooleanField(default=False)),
                ('shipment_terms', models.TextField(max_length=10000000)),
                ('goods_description', models.TextField(max_length=10000000)),
                ('other_lc_terms', models.TextField(max_length=10000000)),
                ('expiry_date', models.DateField()),
                ('lc_amount', models.FloatField(max_length=100000000)),
                ('created_by', models.TextField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 113190, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_master_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master')),
                ('cost_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.cost_center')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.ledger_master')),
                ('year_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.year_master')),
            ],
            options={
                'verbose_name': 'historical lc',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
