# Generated by Django 3.2.5 on 2021-08-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_auto_20210814_2335'),
        ('lc', '0008_auto_20210814_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallc',
            name='bank_ac',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.ledger_master'),
        ),
        migrations.AddField(
            model_name='lc',
            name='bank_ac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_master2', to='Company.ledger_master'),
        ),
        migrations.AlterField(
            model_name='historicallc',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicallc_amend',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicallc_docs',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='lc',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lc',
            name='party_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_master1', to='Company.ledger_master'),
        ),
        migrations.AlterField(
            model_name='lc_amend',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lc_docs',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
