# Generated by Django 3.2.5 on 2021-08-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_alter_ledger_master_docs_ledger_master_id'),
        ('lc', '0009_auto_20210814_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallc_amend',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicallc_docs',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='lc_amend',
            name='company_master_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='lc_docs',
            name='company_master_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
    ]
