# Generated by Django 3.2.5 on 2021-08-12 01:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0009_auto_20210812_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 959059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 959059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 960063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_amend_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 960063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 960063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_docs_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 960063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lc_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 960063, tzinfo=utc)),
        ),
    ]
