# Generated by Django 3.2.5 on 2021-07-28 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acc_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(max_length=1000)),
                ('group_code', models.TextField(max_length=4)),
                ('child_of', models.TextField(max_length=1000, null=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 142330, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='acc_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head_name', models.TextField(max_length=200)),
                ('title', models.TextField(max_length=200)),
                ('bs', models.BooleanField(default=True)),
                ('schedule_no', models.IntegerField()),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 141332, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='company_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(max_length=200, unique=True)),
                ('address', models.TextField(max_length=1000)),
                ('country', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.TextField(max_length=1000, null=True)),
                ('contact_no', models.TextField(max_length=20, null=True)),
                ('cr_no', models.TextField(max_length=500, null=True)),
                ('registration_no', models.TextField(max_length=500, null=True)),
                ('tax_id_no', models.TextField(max_length=500, null=True)),
                ('vat_id_no', models.TextField(max_length=500, null=True)),
                ('year_start_date', models.DateField()),
                ('year_end_date', models.DateField()),
                ('logo', models.ImageField(null=True, upload_to='logo')),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 134333, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='company_master_docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=500)),
                ('file', models.FileField(upload_to='files')),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 137332, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.TextField(max_length=50, unique=True)),
                ('currency_name', models.TextField(max_length=100, unique=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 131331, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ledger_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.TextField(max_length=200)),
                ('old_ledger_id', models.TextField(max_length=200, null=True)),
                ('ledger_name', models.TextField(max_length=200)),
                ('maintain_billwise', models.BooleanField(default=True)),
                ('address', models.TextField(max_length=1000, null=True)),
                ('tel', models.TextField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_person', models.TextField(max_length=50, null=True)),
                ('bank_name', models.TextField(max_length=250, null=True)),
                ('branch_name', models.TextField(max_length=250, null=True)),
                ('bank_code', models.TextField(max_length=250, null=True)),
                ('bank_ac_no', models.TextField(max_length=250, null=True)),
                ('credit_limit', models.TextField(max_length=150, null=True)),
                ('credit_days', models.IntegerField(null=True)),
                ('credit_rating', models.TextField(max_length=150, null=True)),
                ('block_ac', models.BooleanField(default=False, null=True)),
                ('tax_reg_no', models.TextField(max_length=250, null=True)),
                ('cr_no', models.TextField(max_length=250, null=True)),
                ('cr_exp_date', models.DateField(null=True)),
                ('id_no', models.TextField(max_length=250)),
                ('id_exp_date', models.DateField(null=True)),
                ('cc_no', models.TextField(null=True)),
                ('cc_exp_date', models.DateField(null=True)),
                ('vat_no', models.TextField(max_length=250, null=True)),
                ('delivery_terms', models.TextField(max_length=1500, null=True)),
                ('payment_terms', models.TextField(max_length=1500, null=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 144331, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='user_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 136332, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='voucher_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.TextField(max_length=500)),
                ('voucher_class', models.TextField(max_length=500)),
                ('auto_numbering', models.BooleanField(default=False)),
                ('prefix', models.TextField(max_length=200, null=True)),
                ('restart', models.TextField(max_length=50, null=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 140332, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='year_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_no', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 7, 28, 21, 6, 51, 138331, tzinfo=utc))),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
            ],
        ),
    ]
