# Generated by Django 3.2.5 on 2021-07-28 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher_type',
            name='authorization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher_type',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='user_company',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='user_company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_company',
            name='user_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user_group'),
        ),
        migrations.AddField(
            model_name='ledger_master',
            name='acc_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.acc_group'),
        ),
        migrations.AddField(
            model_name='ledger_master',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='company_master_docs',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='company_master',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.currency'),
        ),
        migrations.AddField(
            model_name='acc_head',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='acc_group',
            name='acc_head_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.acc_head'),
        ),
        migrations.AddField(
            model_name='acc_group',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
    ]
