# Generated by Django 3.2.5 on 2021-08-12 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher_type',
            name='authorization_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher_type',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='user_company',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='user_company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_company',
            name='user_group_id',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='Users.user_group'),
        ),
        migrations.AddField(
            model_name='ledger_master',
            name='acc_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.acc_group'),
        ),
        migrations.AddField(
            model_name='ledger_master',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalyear_master',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalyear_master',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvoucher_type',
            name='authorization_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvoucher_type',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalvoucher_type',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluser_company',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicaluser_company',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluser_company',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluser_company',
            name='user_group_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Users.user_group'),
        ),
        migrations.AddField(
            model_name='historicalledger_master',
            name='acc_group_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.acc_group'),
        ),
        migrations.AddField(
            model_name='historicalledger_master',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalledger_master',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcurrency',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcost_center',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalcost_center',
            name='cost_category_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.cost_category'),
        ),
        migrations.AddField(
            model_name='historicalcost_center',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcost_category',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalcost_category',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompany_master_docs',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalcompany_master_docs',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompany_master',
            name='base_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.currency'),
        ),
        migrations.AddField(
            model_name='historicalcompany_master',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalacc_head',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalacc_head',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalacc_group',
            name='acc_head_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.acc_head'),
        ),
        migrations.AddField(
            model_name='historicalacc_group',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalacc_group',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixed_ledger_master',
            name='acc_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.fixed_account_group'),
        ),
        migrations.AddField(
            model_name='fixed_account_group',
            name='acc_head_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.fixed_account_head'),
        ),
        migrations.AddField(
            model_name='cost_center',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='cost_center',
            name='cost_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.cost_category'),
        ),
        migrations.AddField(
            model_name='cost_category',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='company_master_docs',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='company_master',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.currency'),
        ),
        migrations.AddField(
            model_name='acc_head',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='acc_group',
            name='acc_head_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.acc_head'),
        ),
        migrations.AddField(
            model_name='acc_group',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AlterUniqueTogether(
            name='year_master',
            unique_together={('year_no', 'company_master_id')},
        ),
        migrations.AlterUniqueTogether(
            name='voucher_type',
            unique_together={('voucher_name', 'company_master_id')},
        ),
        migrations.AlterUniqueTogether(
            name='user_company',
            unique_together={('user', 'company_master_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cost_center',
            unique_together={('cost_category_id', 'company_master_id')},
        ),
        migrations.AlterUniqueTogether(
            name='acc_head',
            unique_together={('acc_head_name', 'company_master_id')},
        ),
        migrations.AlterUniqueTogether(
            name='acc_group',
            unique_together={('group_name', 'company_master_id')},
        ),
    ]
