# Generated by Django 3.2.5 on 2021-07-29 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 874135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 873103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 869101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 871138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 869101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 875134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 870150, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 872138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 39, 24, 871138, tzinfo=utc)),
        ),
    ]
