# Generated by Django 3.2.5 on 2021-07-29 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_auto_20210729_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 52, 24, 871555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 52, 24, 870555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 52, 24, 867556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 52, 24, 868555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 52, 24, 866557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 52, 24, 871555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 52, 24, 868555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 52, 24, 870555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 8, 52, 24, 869556, tzinfo=utc)),
        ),
    ]
