# Generated by Django 3.2.5 on 2021-08-14 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_auto_20210813_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='child_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.acc_group'),
        ),
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 75564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 69583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 51404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 61388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 81431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 89751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 48318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 92448, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 92448, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 96602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_vouchertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 92448, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalacc_group',
            name='child_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.acc_group'),
        ),
        migrations.AlterField(
            model_name='historicalacc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 75564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalacc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 69583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcompany_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 51404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcompany_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 61388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 81431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 89751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcurrency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 48318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 81431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 51404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalvoucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 68548, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalyear_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 61388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 81431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 51404, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 68548, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 51, 27, 61388, tzinfo=utc)),
        ),
    ]
