# Generated by Django 3.2.5 on 2021-08-14 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_auto_20210814_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='child_of',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 549966, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 545310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 519668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 529396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 562674, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 569968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 514396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 576896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 569968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 578897, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_vouchertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 569968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalacc_group',
            name='child_of',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalacc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 549966, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalacc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 545310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcompany_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 519668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcompany_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 529396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 562674, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 569968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcurrency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 514396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 558111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 522700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalvoucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 540737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalyear_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 530826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 558111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 522700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 540737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 530826, tzinfo=utc)),
        ),
    ]
