# Generated by Django 3.2.5 on 2021-08-14 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_auto_20210814_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 273601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 269479, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 246382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 256800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 285831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 288885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 241659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 297067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 295072, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 298064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_vouchertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 293117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalacc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 273601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalacc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 269479, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcompany_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 246382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcompany_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 256800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 285831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 288885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcurrency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 241659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 280839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 252813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalvoucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 265810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalyear_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 261784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 280839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 252813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 265810, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 17, 14, 54, 261784, tzinfo=utc)),
        ),
    ]
