# Generated by Django 3.2.5 on 2021-08-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0009_auto_20210814_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='acc_head_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acc_group', to='Company.acc_head'),
        ),
        migrations.AlterField(
            model_name='acc_group',
            name='child_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.acc_group'),
        ),
        migrations.AlterField(
            model_name='acc_group',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='cost_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_center', to='Company.cost_category'),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fixed_account_head',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fixed_ledger_master',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fixed_vouchertype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicalacc_group',
            name='child_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.acc_group'),
        ),
        migrations.AlterField(
            model_name='historicalacc_group',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalacc_head',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompany_master',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompany_master_docs',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcost_category',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcost_center',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcurrency',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalledger_master',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaluser_company',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalvoucher_type',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalyear_master',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='acc_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_master', to='Company.acc_group'),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
