# Generated by Django 3.2.5 on 2021-08-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0011_auto_20210814_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='child_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.acc_group'),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='child_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.fixed_account_group'),
        ),
        migrations.AlterField(
            model_name='historicalacc_group',
            name='child_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.acc_group'),
        ),
    ]
