# Generated by Django 3.2.5 on 2021-08-01 08:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0012_auto_20210731_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 406386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 405387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 401388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 403388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 400389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 407386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 402387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 404386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 403388, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='acc_group',
            unique_together={('group_name', 'company_master_id')},
        ),
        migrations.AlterUniqueTogether(
            name='acc_head',
            unique_together={('acc_head_name', 'company_master_id')},
        ),
        migrations.AlterUniqueTogether(
            name='user_company',
            unique_together={('user', 'company_master_id')},
        ),
        migrations.AlterUniqueTogether(
            name='voucher_type',
            unique_together={('voucher_name', 'company_master_id')},
        ),
        migrations.CreateModel(
            name='cost_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 9, 53, 407386, tzinfo=utc))),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
            ],
        ),
    ]
