# Generated by Django 3.2.5 on 2021-08-02 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_auto_20210801_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='fixed_account_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(max_length=1000)),
                ('group_code', models.TextField(max_length=4)),
                ('child_of', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 120408, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='fixed_account_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_head_name', models.TextField(max_length=200)),
                ('title', models.TextField(max_length=200)),
                ('bs', models.BooleanField(default=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 119408, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='fixed_vouchertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.TextField(max_length=500)),
                ('voucher_class', models.TextField(max_length=500)),
                ('auto_numbering', models.BooleanField(default=False)),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 119408, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='year_master',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 118408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 117408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 115408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 116408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 119408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 114408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 118408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 115408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 117408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 116408, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='fixed_ledger_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.TextField(max_length=200)),
                ('ledger_name', models.TextField(max_length=200)),
                ('maintain_billwise', models.BooleanField(default=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 2, 10, 57, 46, 120408, tzinfo=utc))),
                ('acc_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.fixed_account_group')),
            ],
        ),
        migrations.AddField(
            model_name='fixed_account_group',
            name='acc_head_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.fixed_account_head'),
        ),
    ]
