# Generated by Django 3.2.5 on 2021-08-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_auto_20210814_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_center',
            name='child_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.cost_center'),
        ),
        migrations.AlterField(
            model_name='historicalcost_center',
            name='child_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.cost_center'),
        ),
    ]
