# Generated by Django 3.2.5 on 2021-08-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_auto_20210816_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalledger_master',
            name='id_no',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='id_no',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
