# Generated by Django 3.2.5 on 2021-08-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0016_auto_20210817_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_center',
            name='child_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='Company.cost_center'),
        ),
    ]
