# Generated by Django 3.2.5 on 2021-08-05 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_auto_20210804_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 927821, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 925817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 913818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 921817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 931817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 932817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 912818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 954814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 953814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 957818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_vouchertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 952814, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 929817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 915817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 923817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 40, 0, 922817, tzinfo=utc)),
        ),
    ]
