# Generated by Django 3.2.5 on 2021-08-18 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0017_alter_cost_center_child_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger_master_docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=500)),
                ('file', models.FileField(upload_to='ledgerFiles')),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
                ('ledger_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master')),
            ],
        ),
        migrations.CreateModel(
            name='Historicalledger_master_docs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=500)),
                ('file', models.TextField(max_length=100)),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_master_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_master_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.ledger_master')),
            ],
            options={
                'verbose_name': 'historical ledger_master_docs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
