# Generated by Django 3.2.5 on 2021-08-18 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0018_historicalledger_master_docs_ledger_master_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_master_docs',
            name='ledger_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_docs', to='Company.ledger_master'),
        ),
    ]
