# Generated by Django 3.2.5 on 2021-09-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_alter_ledger_master_docs_ledger_master_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ledger_master',
            unique_together={('ledger_id', 'company_master_id')},
        ),
    ]
