# Generated by Django 3.2.5 on 2021-08-10 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0025_auto_20210811_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 90041, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_group_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 91038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 89212, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 90041, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 80103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 84097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 84097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 81101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 95064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 96056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 97042, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 98019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 78073, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 79106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 100053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 99055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 101048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_vouchertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 99055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 93033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 94030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 82103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 83111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 87090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 88090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 85104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 86095, tzinfo=utc)),
        ),
    ]
