# Generated by Django 3.2.5 on 2021-08-11 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0026_auto_20210811_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 370695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_group_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 371692, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 370695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 370695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 364715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 367703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 367703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 365708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 373687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 373687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 374684, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 375259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 363713, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 364715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 376195, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 375259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 376195, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_vouchertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 375259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 371692, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 372689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 366706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 366706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 369698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 369698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 367703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 368700, tzinfo=utc)),
        ),
    ]
