# Generated by Django 3.2.5 on 2021-08-11 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0027_auto_20210811_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 690893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_group_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 690893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 689933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 689933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 684946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 686941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 686941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 685945, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 692924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 693924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 693924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 693924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 683950, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 684946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 694918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 694918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 695917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_vouchertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 694918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 691891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 692924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 685945, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 686941, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 688899, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 688899, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 687939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 30, 38, 687939, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='year_master',
            unique_together={('year_no', 'company_master_id')},
        ),
    ]
