# Generated by Django 3.2.5 on 2021-08-12 01:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0030_auto_20210812_0702'),
        ('Company', '0030_auto_20210811_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalcompany_master',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('company_name', models.TextField(db_index=True, max_length=200)),
                ('address', models.TextField(max_length=1000)),
                ('country', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.TextField(max_length=1000, null=True)),
                ('contact_no', models.TextField(max_length=20, null=True)),
                ('cr_no', models.TextField(max_length=500, null=True)),
                ('registration_no', models.TextField(max_length=500, null=True)),
                ('tax_id_no', models.TextField(max_length=500, null=True)),
                ('vat_id_no', models.TextField(max_length=500, null=True)),
                ('year_start_date', models.DateField()),
                ('year_end_date', models.DateField()),
                ('logo', models.TextField(max_length=100, null=True)),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 90784, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical company_master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalcompany_master_logs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('company_name', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=1000)),
                ('country', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.TextField(max_length=1000, null=True)),
                ('contact_no', models.TextField(max_length=20, null=True)),
                ('base_currency', models.TextField(max_length=500)),
                ('cr_no', models.TextField(max_length=500, null=True)),
                ('registration_no', models.TextField(max_length=500, null=True)),
                ('tax_id_no', models.TextField(max_length=500, null=True)),
                ('vat_id_no', models.TextField(max_length=500, null=True)),
                ('year_start_date', models.DateField()),
                ('year_end_date', models.DateField()),
                ('logo', models.TextField(max_length=100, null=True)),
                ('altered_by', models.TextField()),
                ('altered_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 91783, tzinfo=utc))),
                ('entry', models.TextField(default='before')),
                ('is_deleted', models.BooleanField(default=False)),
                ('operation', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical company_master_logs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalcurrency',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('currency', models.TextField(db_index=True, max_length=50)),
                ('currency_name', models.TextField(db_index=True, max_length=100)),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 89480, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical currency',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaluser_company',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 95815, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical user_company',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='currency_logs',
        ),
        migrations.AddField(
            model_name='company_master',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='currency',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 96813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_group_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 104843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 96813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 96813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 90784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 96813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 96813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 91783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 104843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 104843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 104843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 104843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 89480, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 111190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 110192, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 112190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_vouchertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 110192, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 104843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 104843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 95815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 96813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 96813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 96813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 96813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master_logs',
            name='altered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 96813, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='historicaluser_company',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicaluser_company',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluser_company',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluser_company',
            name='user_group_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Users.user_group'),
        ),
        migrations.AddField(
            model_name='historicalcompany_master',
            name='base_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.currency'),
        ),
        migrations.AddField(
            model_name='historicalcompany_master',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
