# Generated by Django 3.2.5 on 2021-08-12 01:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0031_auto_20210812_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicalacc_group',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('group_name', models.TextField(max_length=1000)),
                ('group_code', models.TextField(max_length=4)),
                ('child_of', models.TextField(max_length=1000, null=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 939983, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical acc_group',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalacc_head',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('acc_head_name', models.TextField(max_length=200)),
                ('title', models.TextField(max_length=200)),
                ('bs', models.BooleanField(default=True)),
                ('schedule_no', models.IntegerField()),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 939983, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical acc_head',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalcompany_master_docs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('doc_name', models.TextField(max_length=500)),
                ('file', models.TextField(max_length=100)),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 924338, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical company_master_docs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalcost_category',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 951002, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical cost_category',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalcost_center',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cost_center_name', models.TextField(max_length=500)),
                ('child_of', models.TextField(default='primary', max_length=500)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 952268, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical cost_center',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalledger_master',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ledger_id', models.TextField(max_length=200)),
                ('old_ledger_id', models.TextField(max_length=200, null=True)),
                ('ledger_name', models.TextField(max_length=200)),
                ('maintain_billwise', models.BooleanField(default=True)),
                ('address', models.TextField(max_length=1000, null=True)),
                ('tel', models.TextField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_person', models.TextField(max_length=50, null=True)),
                ('bank_name', models.TextField(max_length=250, null=True)),
                ('branch_name', models.TextField(max_length=250, null=True)),
                ('bank_code', models.TextField(max_length=250, null=True)),
                ('bank_ac_no', models.TextField(max_length=250, null=True)),
                ('credit_limit', models.TextField(max_length=150, null=True)),
                ('credit_days', models.IntegerField(null=True)),
                ('credit_rating', models.TextField(max_length=150, null=True)),
                ('block_ac', models.BooleanField(default=False, null=True)),
                ('tax_reg_no', models.TextField(max_length=250, null=True)),
                ('cr_no', models.TextField(max_length=250, null=True)),
                ('cr_exp_date', models.DateField(null=True)),
                ('id_no', models.TextField(max_length=250)),
                ('id_exp_date', models.DateField(null=True)),
                ('cc_no', models.TextField(null=True)),
                ('cc_exp_date', models.DateField(null=True)),
                ('vat_no', models.TextField(max_length=250, null=True)),
                ('delivery_terms', models.TextField(max_length=1500, null=True)),
                ('payment_terms', models.TextField(max_length=1500, null=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 948759, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical ledger_master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalvoucher_type',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('voucher_name', models.TextField(max_length=500)),
                ('voucher_class', models.TextField(max_length=500)),
                ('auto_numbering', models.BooleanField(default=False)),
                ('prefix', models.TextField(max_length=200, null=True)),
                ('restart', models.TextField(max_length=50, null=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 939983, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('authorization_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical voucher_type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalyear_master',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('year_no', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=True)),
                ('created_by', models.TextField(max_length=200)),
                ('altered_by', models.TextField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 939983, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical year_master',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name='acc_group_logs',
        ),
        migrations.DeleteModel(
            name='acc_head_logs',
        ),
        migrations.DeleteModel(
            name='company_master_docs_logs',
        ),
        migrations.DeleteModel(
            name='company_master_logs',
        ),
        migrations.DeleteModel(
            name='cost_category_logs',
        ),
        migrations.DeleteModel(
            name='cost_center_logs',
        ),
        migrations.RemoveField(
            model_name='historicalcompany_master_logs',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='ledger_master_logs',
        ),
        migrations.DeleteModel(
            name='user_company_logs',
        ),
        migrations.DeleteModel(
            name='voucher_type_logs',
        ),
        migrations.DeleteModel(
            name='year_master_logs',
        ),
        migrations.AddField(
            model_name='acc_group',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='acc_head',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company_master_docs',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cost_category',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicaluser_company',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ledger_master',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user_company',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='voucher_type',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='year_master',
            name='altered_by',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='acc_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 939983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acc_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 939983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 924338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company_master_docs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 924338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 951002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 952268, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 924338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_group',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 956608, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_account_head',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 953272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 957614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fixed_vouchertype',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 953272, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcompany_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 924338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalcurrency',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 924338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaluser_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 924338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 948759, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_company',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 924338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='voucher_type',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 939983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='year_master',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 45, 7, 939983, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Historicalcompany_master_logs',
        ),
        migrations.AddField(
            model_name='historicalyear_master',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalyear_master',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvoucher_type',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalvoucher_type',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalledger_master',
            name='acc_group_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.acc_group'),
        ),
        migrations.AddField(
            model_name='historicalledger_master',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalledger_master',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcost_center',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalcost_center',
            name='cost_category_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.cost_category'),
        ),
        migrations.AddField(
            model_name='historicalcost_center',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcost_category',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalcost_category',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompany_master_docs',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalcompany_master_docs',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalacc_head',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalacc_head',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalacc_group',
            name='acc_head_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.acc_head'),
        ),
        migrations.AddField(
            model_name='historicalacc_group',
            name='company_master_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master'),
        ),
        migrations.AddField(
            model_name='historicalacc_group',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
