# Generated by Django 3.2.5 on 2021-08-10 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0025_auto_20210811_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('dr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('cr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('fc_amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('fc_rate', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('total_dr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('total_cr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 30, 47, 334711, tzinfo=utc))),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
                ('fc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.currency')),
                ('ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.ledger_master')),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.year_master')),
            ],
            options={
                'unique_together': {('ledger_id', 'year_id')},
            },
        ),
        migrations.CreateModel(
            name='ledger_bal_billwise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_code', models.TextField(max_length=200)),
                ('name', models.TextField(max_length=200)),
                ('chq_date', models.DateField(null=True)),
                ('chq_no', models.IntegerField(max_length=200, null=True)),
                ('transaction_date', models.DateField(null=True)),
                ('transaction_no', models.IntegerField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('remarks', models.TextField(max_length=200, null=True)),
                ('transaction_type', models.TextField(max_length=200, null=True)),
                ('reco_date', models.DateField(null=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 30, 47, 375422, tzinfo=utc))),
                ('bank_ledger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_balance.ledger_balance')),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
            ],
        ),
    ]
