# Generated by Django 3.2.5 on 2021-08-12 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_auto_20210812_1923'),
        ('ledger_balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalop_bal_brs',
            name='year_id',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.year_master'),
        ),
        migrations.AddField(
            model_name='op_bal_brs',
            name='year_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Company.year_master'),
        ),
        migrations.AlterField(
            model_name='historicalledger_bal_billwise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 13, 53, 23, 358119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalledger_balance',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 13, 53, 23, 352135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalop_bal_brs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 13, 53, 23, 360655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_bal_billwise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 13, 53, 23, 358119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_balance',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 13, 53, 23, 352135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='op_bal_brs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 13, 53, 23, 360655, tzinfo=utc)),
        ),
    ]
