# Generated by Django 3.2.5 on 2021-08-10 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0026_auto_20210811_0105'),
        ('ledger_balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='op_bal_brs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_code', models.TextField(max_length=200)),
                ('name', models.TextField(max_length=200)),
                ('chq_date', models.DateField(null=True)),
                ('chq_no', models.IntegerField(max_length=200, null=True)),
                ('transaction_date', models.DateField(null=True)),
                ('transaction_no', models.IntegerField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('remarks', models.TextField(max_length=200, null=True)),
                ('transaction_type', models.TextField(max_length=200, null=True)),
                ('reco_date', models.DateField(null=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 142872, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='ledger_balance',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 19, 35, 33, 140834, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ledger_bal_billwise',
        ),
        migrations.AddField(
            model_name='op_bal_brs',
            name='bank_ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_balance.ledger_balance'),
        ),
        migrations.AddField(
            model_name='op_bal_brs',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master'),
        ),
    ]
