# Generated by Django 3.2.5 on 2021-08-11 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0027_auto_20210811_1520'),
        ('ledger_balance', '0002_auto_20210811_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_balance',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 390435, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='op_bal_brs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 402534, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ledger_bal_billwise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.TextField(max_length=100)),
                ('bill_date', models.DateField(null=True)),
                ('dr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('cr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('due_date', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('fc_amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('fc_rate', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 11, 9, 50, 29, 401537, tzinfo=utc))),
                ('company_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company_master')),
                ('fc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.currency')),
                ('ledger_bal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger_balance.ledger_balance')),
            ],
            options={
                'unique_together': {('ledger_bal_id', 'ref_no')},
            },
        ),
    ]
