# Generated by Django 3.2.5 on 2021-08-14 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_balance', '0004_auto_20210814_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalledger_bal_billwise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 617746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalledger_balance',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 608832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalop_bal_brs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 623535, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_bal_billwise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 617746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_balance',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 608832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='op_bal_brs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 8, 4, 26, 623535, tzinfo=utc)),
        ),
    ]
