# Generated by Django 3.2.5 on 2021-08-12 01:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0031_auto_20210812_0702'),
        ('ledger_balance', '0006_auto_20210811_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_bal_billwise',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 122602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ledger_balance',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 121815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='op_bal_brs',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 122602, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Historicalop_bal_brs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('acc_code', models.TextField(max_length=200)),
                ('name', models.TextField(max_length=200)),
                ('chq_date', models.DateField(null=True)),
                ('chq_no', models.IntegerField(max_length=200, null=True)),
                ('transaction_date', models.DateField(null=True)),
                ('transaction_no', models.IntegerField(max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('remarks', models.TextField(max_length=200, null=True)),
                ('transaction_type', models.TextField(max_length=200, null=True)),
                ('reco_date', models.DateField(null=True)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 122602, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_ledger_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger_balance.ledger_balance')),
                ('company_master_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical op_bal_brs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalledger_balance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('dr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('cr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('fc_amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('fc_rate', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('total_dr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('total_cr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 121815, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_master_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master')),
                ('fc_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.ledger_master')),
                ('year_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.year_master')),
            ],
            options={
                'verbose_name': 'historical ledger_balance',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalledger_bal_billwise',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ref_no', models.TextField(max_length=100)),
                ('bill_date', models.DateField(null=True)),
                ('dr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('cr', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('due_date', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('fc_amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('fc_rate', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('created_by', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 1, 31, 56, 122602, tzinfo=utc))),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company_master_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.company_master')),
                ('fc_name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Company.currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_bal_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger_balance.ledger_balance')),
            ],
            options={
                'verbose_name': 'historical ledger_bal_billwise',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
