# Generated by Django 3.2.5 on 2021-08-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_balance', '0008_auto_20210814_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalledger_bal_billwise',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalledger_balance',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalop_bal_brs',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='ledger_bal_billwise',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ledger_balance',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='op_bal_brs',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
