# Generated by Django 3.2.5 on 2021-08-26 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_alter_ledger_master_docs_ledger_master_id'),
        ('ledger_balance', '0013_alter_ledger_bal_billwise_ledger_bal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_balance',
            name='ledger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_balance', to='Company.ledger_master'),
        ),
    ]
