# Generated by Django 3.2.5 on 2021-09-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0021_auto_20210904_1328'),
        ('ledger_balance', '0017_auto_20210903_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_bal_billwise',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='ledger_bal_billwise',
            name='fc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.currency'),
        ),
        migrations.AlterField(
            model_name='ledger_balance',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
        migrations.AlterField(
            model_name='op_bal_brs',
            name='company_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Company.company_master'),
        ),
    ]
